
spring:
  application:
    name: nobug-shop-service-search
  data:
    solr:
      host: http://47.111.247.209:8983/solr/ik_core
    datasource:
      url: jdbc:mysql://47.98.124.70:3306/nobug?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      druid:
        driver: com.mysql.jdbc.Driver



server:
  port: 7777

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

imageService: http://localhsot