server:
  port: 8766

spring:
  application:
    name: nobug-shop-service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  rabbitmq:
    host: 47.98.124.70
      port: 5672
      username: root
      password: 123456
      virtual-host: nz
    listener:
      direct:
        acknowledge-mode: manual   # 配置该消费者的ack方式为手动

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



  devtools:
    restart:
      enabled: false #