spring:
  rabbitmq:
    host: 47.98.124.70
    port: 5672
    username: root
    password: 123456
    virtual-host: nz
  application:
    name: nobug-shop-service-mq
server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


