server:
  port: 8080

spring:
  application:
    name: nobug-shop-web-index

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 45000

ribbon:
  connectTimeout: 5000
  readTimeout: 10000