server:
  port: 80

spring:
  application:
    name: nobug-shop-web-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/