spring:
  application:
    name: nobug-shop-web-down-order

server:
  port: 7780


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

