spring:
  application:
    name: springcloud-netflix-eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: 47.98.124.70
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/