spring:
  application:
    name: springcloud-netflix-eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: htance.hostname}:${server.port}/eureka/tp://${eureka.inst