server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: nobug-shop-web-register

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000


