server:
  port: 8100

spring:
  application:
    name: nobug-shop-mapper-user-info
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.124.70:3306/shop?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: entity

logging:
  level:
    com:
      nobug:
        mapper: debug