spring:
  # 配置邮件发送账号
  mail:
    host: smtp.qq.com
    username: 964443622@qq.com
    password: zjjolsvqrrnebbai
    default-encoding: utf-8
  application:
    name: nobug-shop-service-send-mail

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

activeServerUrl: http://localhost:8081/user/active/account/