spring:
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: utf-8
  application:
    name: nobug-shop-service-send-mail

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# todo redis≈‰÷√
